ffn_natation_utilisateurrole:
    resource: "@FFNNatationBundle/Controller/administration/UtilisateurRoleController.php"
    type:     annotation

ffn_natation_noter:
    resource: "@FFNNatationBundle/Controller/administration/NoterController.php"
    type:     annotation

ffn_natation_composer:
    resource: "@FFNNatationBundle/Controller/administration/ComposerController.php"
    type:     annotation

ffn_natation_utilisateur:
    resource: "@FFNNatationBundle/Controller/administration/UtilisateurController.php"
    type:     annotation

ffn_natation_role:
    resource: "@FFNNatationBundle/Controller/administration/RoleController.php"
    type:     annotation

ffn_natation_equipe:
    resource: "@FFNNatationBundle/Controller/administration/EquipeController.php"
    type:     annotation

ffn_natation_club:
    resource: "@FFNNatationBundle/Controller/administration/ClubController.php"
    type:     annotation

ffn_natation_competition:
    resource: "@FFNNatationBundle/Controller/administration/CompetitionController.php"
    type:     annotation

ffn_natation_lieu:
    resource: "@FFNNatationBundle/Controller/administration/LieuController.php"
    type:     annotation

ffn_natation_personne:
    resource: "@FFNNatationBundle/Controller/administration/PersonneController.php"
    type:     annotation

ffn_natation_admin:
    resource: "@FFNNatationBundle/Controller/administration/AdminController.php"
    type:     annotation

ffn_natation:
    resource: "@FFNNatationBundle/Resources/config/routing.yml"
    prefix:   /

_default:
    resource: "@FFNNatationBundle/Controller/"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"