ffn_natation:
    resource: "@FFNNatationBundle/Resources/config/routing.yml"
    prefix:   /

_default:
    resource: "@FFNNatationBundle/Controller/"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
