<?php

namespace FFN\NatationBundle\Repository;

/**
 * ComposerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposerRepository extends \Doctrine\ORM\EntityRepository
{
}
