ffn_natation_homepage:
    path:     /
    defaults: { _controller: FFNNatationBundle:Natation:view }

view:
    path:     ffn_natation_view
    defaults: { _controller: FFNNatationBundle:Natation:view }
