ffn_natation_homepage:
    path:     /
    defaults: { _controller: FFNNatationBundle:Natation:view }

view:
    path:     ffn_natation_view
    defaults: { _controller: FFNNatationBundle:Natation:view }

competitions:
    path:     /competitions
    defaults: { _controller: FFNNatationBundle:Natation:competitions }

services:
    path:     /services
    defaults: { _controller: FFNNatationBundle:Natation:services }

profiles:
    path:     /profiles
    defaults: { _controller: FFNNatationBundle:Natation:profiles }

ffn_natation_info:
    path:     /competitions/{id}
    defaults:
        _controller: FFNNatationBundle:Natation:information
    requirements:
        id: \d+

ffn_natation_equipe:
    path:     /equipe/{id}
    defaults:
        _controller: FFNNatationBundle:Natation:equipe
    requirements:
        id: \d+

ffn_natation_information_nageur:
    path:     /personne/{id}
    defaults:
        _controller: FFNNatationBundle:Natation:information_nageur
    requirements:
        id: \d+