ffn_natation_homepage:
    path:     /
    defaults: { _controller: FFNNatationBundle:Natation:view }

view:
    path:     ffn_natation_view
    defaults: { _controller: FFNNatationBundle:Natation:view }

concours:
    path:     /concours
    defaults: { _controller: FFNNatationBundle:Natation:concours }

services:
    path:     /services
    defaults: { _controller: FFNNatationBundle:Natation:services }

profiles:
    path:     /profiles
    defaults: { _controller: FFNNatationBundle:Natation:profiles }

ffn_natation_info:
    path:     /concours/{id}
    defaults:
        _controller: FFNNatationBundle:Natation:information
    requirements:
        id: \d+

ffn_natation_groupe:
    path:     /groupe/{id}
    defaults:
        _controller: FFNNatationBundle:Natation:groupe
    requirements:
        id: \d+